name: 'Normalize PR Title and Add Jira Link'
description: 'Automatically formats PR titles to Jira key format (PDD-123) and appends a Jira link to the PR body.'
author: 'vkozlov-sit'

branding:
  icon: 'link'
  color: 'blue'

inputs:
  jira-project-key:
    description: 'Jira Project Key to be included in the PR title and body, e.g. PDD-123'
    required: true
  github-token:
    description: 'GitHub token with pull-requests: write permission'
    required: true
    default: '${{ github.token }}'

runs:
  using: 'node20'
  main: 'dist/index.js'
